name: "Go"
on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - "**.md"

  pull_request:
    types: [ opened, synchronize ]
    paths-ignore:
      - "**.md"

  workflow_dispatch:

jobs:
  fmt:
    name: Format Go code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Setup Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: 1.20

      - name: Download modules
        run: |
          cd 2.3.0
          go mod download

      - name: Format
        run: go fmt ./2.3.0/...