name: "Validate OpenAPI specification"
on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - "**.md"

  pull_request:
    types: [ opened, synchronize ]
    paths-ignore:
      - "**.md"

  workflow_dispatch:

jobs:
  validate-v20-specification:
    name: "Validate the OSCP 2.0 OpenAPI specification"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Swagger Editor Validator
        id: validate
        uses: swaggerexpert/swagger-editor-validate@v1
        with:
          definition-file: ./2.0/api/2.0.spec.yaml

      - name: Setup Go
        if: steps.validate.outcome == 'success'
        uses: actions/setup-go@v6
        with:
          go-version: 1.23.0

      - name: Install Oapi Codegen
        if: steps.validate.outcome == 'success'
        working-directory: ./2.0
        run: |
          go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest
          go generate ./...

      - name: Push the generated code
        uses: stefanzweifel/git-auto-commit-action@v7
        if: github.event_name == 'pull_request'
        with:
          commit_message: "[Autogen] Generated client and server code from OpenAPI spec"

      - name: Create a pull request
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "[Autogen] Generated client and server code from OpenAPI spec"
          title: "[Autogen] OpenAPI client update"
          body: "OpenAPI client and server were (re)generated from the latest OpenAPI spec."
          branch: "openapi/autogen-${{ github.sha }}"
          base: main
          labels: autogen